import type { Metadata } from "next";
import { Montserrat, Roboto, Inter } from "next/font/google";
import "./globals.css";

const montFont = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const interFont = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const robotoFont = Roboto({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montFont.className} antialiased`}>{children}</body>
    </html>
  );
}
