"""empty message

Revision ID: 6050c3f96c06
Revises: b1192855028c
Create Date: 2025-08-27 19:31:21.223183

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6050c3f96c06"
down_revision: Union[str, Sequence[str], None] = "b1192855028c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "credit_card_table",
        sa.Column("payment_id", sa.String(length=150), nullable=True),
    )
    op.add_column(
        "credit_card_table",
        sa.Column("payment_method", sa.String(length=64), nullable=False),
    )
    op.add_column(
        "credit_card_table", sa.Column("expiry_month", sa.Integer(), nullable=False)
    )
    op.add_column(
        "credit_card_table", sa.Column("expiry_year", sa.Integer(), nullable=False)
    )
    op.drop_column("credit_card_table", "stripe_payment_method_id")
    op.drop_column("credit_card_table", "expirty_date")
    op.add_column(
        "subscriptions_table",
        sa.Column("paddle_product_id", sa.String(length=150), nullable=True),
    )
    op.add_column(
        "subscriptions_table",
        sa.Column("paddle_subscription_id", sa.String(length=150), nullable=True),
    )
    op.add_column(
        "subscriptions_table",
        sa.Column("paddle_price_id", sa.String(length=150), nullable=True),
    )
    op.add_column(
        "subscriptions_table",
        sa.Column("subscription_tier", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "subscriptions_table",
        sa.Column("paddle_subscription_status", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "subscriptions_table",
        sa.Column("subscription_created_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "subscriptions_table",
        sa.Column("subscription_next_billed_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "subscriptions_table",
        sa.Column("total_money_spent", sa.Float(), nullable=True, default=0),
    )
    op.add_column(
        "subscriptions_table",
        sa.Column("billing_interval", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "subscriptions_table",
        sa.Column("billing_frequency", sa.Integer(), nullable=True),
    )
    op.drop_column("subscriptions_table", "sub_tier")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions_table",
        sa.Column("sub_tier", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("subscriptions_table", "billing_frequency")
    op.drop_column("subscriptions_table", "billing_interval")
    op.drop_column("subscriptions_table", "total_money_spent")
    op.drop_column("subscriptions_table", "subscription_next_billed_at")
    op.drop_column("subscriptions_table", "subscription_created_at")
    op.drop_column("subscriptions_table", "paddle_subscription_status")
    op.drop_column("subscriptions_table", "subscription_tier")
    op.drop_column("subscriptions_table", "paddle_price_id")
    op.drop_column("subscriptions_table", "paddle_subscription_id")
    op.drop_column("subscriptions_table", "paddle_product_id")
    op.add_column(
        "credit_card_table",
        sa.Column(
            "expirty_date", sa.VARCHAR(length=7), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "credit_card_table",
        sa.Column(
            "stripe_payment_method_id",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("credit_card_table", "expiry_year")
    op.drop_column("credit_card_table", "expiry_month")
    op.drop_column("credit_card_table", "payment_method")
    op.drop_column("credit_card_table", "payment_id")
    # ### end Alembic commands ###
