"""empty message

Revision ID: 6846912b189f
Revises: 66b1a3a59ce2
Create Date: 2025-09-06 21:40:06.614760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6846912b189f'
down_revision: Union[str, Sequence[str], None] = '66b1a3a59ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions_table', sa.Column('paddle_update_url', sa.String(length=2000), nullable=True))
    op.add_column('subscriptions_table', sa.Column('paddle_cancel_url', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions_table', 'paddle_cancel_url')
    op.drop_column('subscriptions_table', 'paddle_update_url')
    # ### end Alembic commands ###
