"""empty message

Revision ID: 7ecafe8f1c5e
Revises: 4337c95e354c
Create Date: 2025-08-13 09:06:25.504212

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import fastapi_users_db_sqlalchemy.generics

# revision identifiers, used by Alembic.
revision: str = "7ecafe8f1c5e"
down_revision: Union[str, Sequence[str], None] = "4337c95e354c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "Ongoing", "Finished", "Cancelled", "Paused", name="test_status_enum"
    ).create(op.get_bind(), checkfirst=True)
    op.create_table(
        "reading_cards_table",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "practice_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["practice_id"],
            ["practice_test_table.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_cards_table_practice_id"),
        "reading_cards_table",
        ["practice_id"],
        unique=False,
    )
    op.add_column(
        "practice_test_table",
        sa.Column(
            "status",
            sa.Enum(
                "ONGOING", "FINISHED", "CANCELLED", "PAUSED", name="test_status_enum"
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "result_table",
        sa.Column(
            "strong_points", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
    )
    op.drop_column("result_table", "strong_sides")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "result_table",
        sa.Column(
            "strong_sides",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("result_table", "strong_points")
    op.drop_column("practice_test_table", "status")
    op.drop_index(
        op.f("ix_reading_cards_table_practice_id"), table_name="reading_cards_table"
    )
    op.drop_table("reading_cards_table")
    sa.Enum("Ongoing", "Finished", "Cancelled", "Paused", name="test_status_enum").drop(
        op.get_bind(), checkfirst=True
    )
    # ### end Alembic commands ###
