"""empty message

Revision ID: 93fb97caca28
Revises: a14b6132a2f0
Create Date: 2025-10-12 17:03:41.017886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93fb97caca28'
down_revision: Union[str, Sequence[str], None] = 'a14b6132a2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_card_table')
    op.add_column('subscriptions_table', sa.Column('polar_product_id', sa.String(length=150), nullable=True))
    op.add_column('subscriptions_table', sa.Column('polar_subscription_id', sa.String(length=150), nullable=True))
    op.add_column('subscriptions_table', sa.Column('polar_customer_id', sa.String(length=150), nullable=True))
    op.add_column('subscriptions_table', sa.Column('polar_price_id', sa.String(length=150), nullable=True))
    op.add_column('subscriptions_table', sa.Column('polar_subscription_status', sa.String(length=20), nullable=True))
    op.add_column('subscriptions_table', sa.Column('subscription_cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('subscriptions_table', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('subscriptions_table', sa.Column('cancellation_comment', sa.Text(), nullable=True))
    op.drop_column('subscriptions_table', 'paddle_cancel_url')
    op.drop_column('subscriptions_table', 'paddle_update_url')
    op.drop_column('subscriptions_table', 'paddle_subscription_status')
    op.drop_column('subscriptions_table', 'paddle_price_id')
    op.drop_column('subscriptions_table', 'paddle_subscription_id')
    op.drop_column('subscriptions_table', 'paddle_product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions_table', sa.Column('paddle_product_id', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('subscriptions_table', sa.Column('paddle_subscription_id', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('subscriptions_table', sa.Column('paddle_price_id', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('subscriptions_table', sa.Column('paddle_subscription_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('subscriptions_table', sa.Column('paddle_update_url', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.add_column('subscriptions_table', sa.Column('paddle_cancel_url', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.drop_column('subscriptions_table', 'cancellation_comment')
    op.drop_column('subscriptions_table', 'cancellation_reason')
    op.drop_column('subscriptions_table', 'subscription_cancelled_at')
    op.drop_column('subscriptions_table', 'polar_subscription_status')
    op.drop_column('subscriptions_table', 'polar_price_id')
    op.drop_column('subscriptions_table', 'polar_customer_id')
    op.drop_column('subscriptions_table', 'polar_subscription_id')
    op.drop_column('subscriptions_table', 'polar_product_id')
    op.create_table('credit_card_table',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('card_holder_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('card_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('last_four', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('expiry_month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expiry_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions_table.id'], name=op.f('credit_card_table_subscription_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_card_table_pkey'))
    )
    # ### end Alembic commands ###
