"""empty message

Revision ID: d861d655c240
Revises: 3b7f680980b4
Create Date: 2025-08-17 08:50:42.069009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd861d655c240'
down_revision: Union[str, Sequence[str], None] = '3b7f680980b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions_table', sa.Column('part_one', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('transcriptions_table', sa.Column('part_two', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('transcriptions_table', sa.Column('part_three', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('transcriptions_table', 'user_responses')
    op.drop_column('transcriptions_table', 'assistant_responses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions_table', sa.Column('assistant_responses', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('transcriptions_table', sa.Column('user_responses', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('transcriptions_table', 'part_three')
    op.drop_column('transcriptions_table', 'part_two')
    op.drop_column('transcriptions_table', 'part_one')
    # ### end Alembic commands ###
