"""empty message

Revision ID: df3c27a4468b
Revises: 103c08bb00e1
Create Date: 2025-08-26 22:37:44.786821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "df3c27a4468b"
down_revision: Union[str, Sequence[str], None] = "103c08bb00e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analytics_table",
        sa.Column(
            "grammar_common_mistakes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "analytics_table",
        sa.Column(
            "lexis_common_mistakes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "analytics_table",
        sa.Column(
            "pronunciation_common_mistakes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.drop_column("analytics_table", "common_mistakes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analytics_table",
        sa.Column(
            "common_mistakes",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("analytics_table", "pronunciation_common_mistakes")
    op.drop_column("analytics_table", "lexis_common_mistakes")
    op.drop_column("analytics_table", "grammar_common_mistakes")
    # ### end Alembic commands ###
