"""empty message

Revision ID: fcf5a8fa8a9e
Revises: 6050c3f96c06
Create Date: 2025-08-28 12:15:18.759829

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fcf5a8fa8a9e"
down_revision: Union[str, Sequence[str], None] = "6050c3f96c06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "credit_card_table",
        "card_holder_name",
        existing_type=sa.VARCHAR(length=150),
        nullable=True,
    )
    op.alter_column(
        "subscriptions_table",
        "total_money_spent",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscriptions_table",
        "total_money_spent",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "credit_card_table",
        "card_holder_name",
        existing_type=sa.VARCHAR(length=150),
        nullable=False,
    )
    # ### end Alembic commands ###
