"""empty message

Revision ID: 113cf9c1bb36
Revises: ed2e786b76e9
Create Date: 2025-08-15 10:29:37.625625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113cf9c1bb36'
down_revision: Union[str, Sequence[str], None] = 'ed2e786b76e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('user_table', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'last_name')
    op.drop_column('user_table', 'first_name')
    # ### end Alembic commands ###
