"""empty message

Revision ID: 123983bb4834
Revises: 3e6e48576073
Create Date: 2025-09-09 12:58:55.789220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '123983bb4834'
down_revision: Union[str, Sequence[str], None] = '3e6e48576073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_table', sa.Column('scores_increase', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics_table', 'scores_increase')
    # ### end Alembic commands ###
