"""empty message

Revision ID: 28b3f6784f81
Revises: be9a42e7dda9
Create Date: 2025-11-01 21:37:03.738139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28b3f6784f81"
down_revision: Union[str, Sequence[str], None] = "be9a42e7dda9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications_table", sa.Column("is_read", sa.Boolean(), default=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notifications_table", "is_read")
    # ### end Alembic commands ###
