"""empty message

Revision ID: 38d84c2d16ae
Revises: 113cf9c1bb36
Create Date: 2025-08-15 15:57:17.049041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "38d84c2d16ae"
down_revision: Union[str, Sequence[str], None] = "113cf9c1bb36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE question_cards_table
        ALTER COLUMN part
        TYPE INTEGER
        USING (
            CASE
                WHEN part = 'PART_ONE' THEN 1
                WHEN part = 'PART_TWO' THEN 2
            END
        )
    """
    )
    op.alter_column(
        "practice_test_table",
        "status",
        existing_type=postgresql.ENUM(
            "Ongoing", "Finished", "Cancelled", "Paused", name="test_status_enum"
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "practice_test_table",
        "assistant",
        existing_type=postgresql.ENUM("RON", "EMMA", name="assistant_enum"),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "question_cards_table",
        "part",
        existing_type=postgresql.ENUM("PART_ONE", "PART_TWO", name="test_part_enum"),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.add_column(
        "subscriptions_table", sa.Column("sub_tier", sa.String(), nullable=False)
    )

    op.execute("DROP TYPE IF EXISTS test_part_enum")
    op.execute("DROP TYPE IF EXISTS assistant_enum")
    op.execute("DROP TYPE IF EXISTS test_status_enum")
    op.execute("DROP TYPE IF EXISTS subscription_tier_enum")
    op.drop_column("subscriptions_table", "subscription_tier_enum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions_table",
        sa.Column(
            "subscription_tier_enum",
            postgresql.ENUM("Free", "STARTER", "PRO", name="subscriptionenum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("subscriptions_table", "sub_tier")
    op.alter_column(
        "question_cards_table",
        "part",
        existing_type=sa.Integer(),
        type_=postgresql.ENUM("PART_ONE", "PART_TWO", name="test_part_enum"),
        existing_nullable=False,
    )
    op.alter_column(
        "practice_test_table",
        "assistant",
        existing_type=sa.String(),
        type_=postgresql.ENUM("RON", "EMMA", name="assistant_enum"),
        existing_nullable=False,
    )
    op.alter_column(
        "practice_test_table",
        "status",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "Ongoing", "Finished", "Cancelled", "Paused", name="test_status_enum"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
