"""empty message

Revision ID: 684a27479b07
Revises: 7ecafe8f1c5e
Create Date: 2025-08-14 15:48:35.718842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '684a27479b07'
down_revision: Union[str, Sequence[str], None] = '7ecafe8f1c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pronunciation_test_table',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('pronunciation_score', sa.FLOAT(), nullable=False),
    sa.Column('pronunciation_strong_points', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('pronunciation_weak_sides', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('pronunciation_mistakes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pronunciation_tips', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pronunciation_test_table_user_id'), 'pronunciation_test_table', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pronunciation_test_table_user_id'), table_name='pronunciation_test_table')
    op.drop_table('pronunciation_test_table')
    # ### end Alembic commands ###
