"""empty message

Revision ID: 69fcc2b935f4
Revises: cb1f08d48d72
Create Date: 2025-10-12 23:24:08.994377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69fcc2b935f4'
down_revision: Union[str, Sequence[str], None] = 'cb1f08d48d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'last_login_at')
    # ### end Alembic commands ###
