"""empty message

Revision ID: 84d0adf1723f
Revises: ebcc33e3bfcf
Create Date: 2025-08-26 23:38:02.654134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d0adf1723f'
down_revision: Union[str, Sequence[str], None] = 'ebcc33e3bfcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications_table', sa.Column('time', sa.DateTime(), nullable=False))
    op.drop_column('notifications_table', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications_table', sa.Column('link', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('notifications_table', 'time')
    # ### end Alembic commands ###
