"""empty message

Revision ID: a14b6132a2f0
Revises: 
Create Date: 2025-09-28 12:21:05.599435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a14b6132a2f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_cards_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('questions', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('avatar_path', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_table_email'), 'user_table', ['email'], unique=True)
    op.create_table('analytics_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('practice_time', sa.Integer(), nullable=False),
    sa.Column('tests_completed', sa.Integer(), nullable=False),
    sa.Column('current_bandscore', sa.Float(), nullable=False),
    sa.Column('average_band_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scores_increase', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('average_band', sa.Float(), nullable=False),
    sa.Column('grammar_common_mistakes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lexis_common_mistakes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pronunciation_common_mistakes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_table_user_id'), 'analytics_table', ['user_id'], unique=False)
    op.create_table('notifications_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(length=250), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_table_user_id'), 'notifications_table', ['user_id'], unique=False)
    op.create_table('oauth_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('oauth_name', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('account_id', sa.String(length=320), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_account_account_id'), 'oauth_account', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_account_oauth_name'), 'oauth_account', ['oauth_name'], unique=False)
    op.create_table('practice_test_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('practice_name', sa.String(length=100), nullable=False),
    sa.Column('assistant', sa.String(), nullable=False),
    sa.Column('test_duration', sa.Integer(), nullable=True),
    sa.Column('test_date', sa.DateTime(), nullable=False),
    sa.Column('part_one_card_id', sa.UUID(), nullable=True),
    sa.Column('part_two_card_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['part_one_card_id'], ['question_cards_table.id'], ),
    sa.ForeignKeyConstraint(['part_two_card_id'], ['question_cards_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_test_table_part_one_card_id'), 'practice_test_table', ['part_one_card_id'], unique=False)
    op.create_index(op.f('ix_practice_test_table_part_two_card_id'), 'practice_test_table', ['part_two_card_id'], unique=False)
    op.create_index(op.f('ix_practice_test_table_user_id'), 'practice_test_table', ['user_id'], unique=False)
    op.create_table('pronunciation_test_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pronunciation_score', sa.FLOAT(), nullable=False),
    sa.Column('pronunciation_strong_points', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('pronunciation_weak_sides', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('pronunciation_mistakes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pronunciation_tips', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pronunciation_test_table_user_id'), 'pronunciation_test_table', ['user_id'], unique=False)
    op.create_table('questionnaire_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('heard_from', sa.String(length=100), nullable=True),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('test_experience', sa.Float(), nullable=True),
    sa.Column('ui_intuitivity', sa.Float(), nullable=True),
    sa.Column('eval_accuracy', sa.Float(), nullable=True),
    sa.Column('suggestion', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_table_user_id'), 'questionnaire_table', ['user_id'], unique=False)
    op.create_table('subscriptions_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('paddle_product_id', sa.String(length=150), nullable=True),
    sa.Column('paddle_subscription_id', sa.String(length=150), nullable=True),
    sa.Column('paddle_price_id', sa.String(length=150), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('paddle_subscription_status', sa.String(length=20), nullable=True),
    sa.Column('subscription_created_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_next_billed_at', sa.DateTime(), nullable=True),
    sa.Column('total_money_spent', sa.Float(), nullable=True),
    sa.Column('credits_total_purchased', sa.Integer(), nullable=False),
    sa.Column('credits_left', sa.Integer(), nullable=False),
    sa.Column('billing_interval', sa.String(length=20), nullable=True),
    sa.Column('billing_frequency', sa.Integer(), nullable=True),
    sa.Column('paddle_update_url', sa.String(length=2000), nullable=True),
    sa.Column('paddle_cancel_url', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_table_user_id'), 'subscriptions_table', ['user_id'], unique=False)
    op.create_table('credit_card_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.String(length=150), nullable=True),
    sa.Column('payment_method', sa.String(length=64), nullable=False),
    sa.Column('card_holder_name', sa.String(length=150), nullable=True),
    sa.Column('card_type', sa.String(length=30), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=False),
    sa.Column('expiry_month', sa.Integer(), nullable=False),
    sa.Column('expiry_year', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_cards_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['practice_test_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_cards_table_practice_id'), 'reading_cards_table', ['practice_id'], unique=False)
    op.create_table('result_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_test_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('criterion_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weak_sides', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strong_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sentence_improvements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grammar_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vocabulary_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('repeated_words', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pronunciation_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('general_tips', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['practice_test_id'], ['practice_test_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_table_practice_test_id'), 'result_table', ['practice_test_id'], unique=False)
    op.create_table('transcriptions_table',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('part_one', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('part_two', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('part_three', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['practice_test_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcriptions_table_user_id'), 'transcriptions_table', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcriptions_table_user_id'), table_name='transcriptions_table')
    op.drop_table('transcriptions_table')
    op.drop_index(op.f('ix_result_table_practice_test_id'), table_name='result_table')
    op.drop_table('result_table')
    op.drop_index(op.f('ix_reading_cards_table_practice_id'), table_name='reading_cards_table')
    op.drop_table('reading_cards_table')
    op.drop_table('credit_card_table')
    op.drop_index(op.f('ix_subscriptions_table_user_id'), table_name='subscriptions_table')
    op.drop_table('subscriptions_table')
    op.drop_index(op.f('ix_questionnaire_table_user_id'), table_name='questionnaire_table')
    op.drop_table('questionnaire_table')
    op.drop_index(op.f('ix_pronunciation_test_table_user_id'), table_name='pronunciation_test_table')
    op.drop_table('pronunciation_test_table')
    op.drop_index(op.f('ix_practice_test_table_user_id'), table_name='practice_test_table')
    op.drop_index(op.f('ix_practice_test_table_part_two_card_id'), table_name='practice_test_table')
    op.drop_index(op.f('ix_practice_test_table_part_one_card_id'), table_name='practice_test_table')
    op.drop_table('practice_test_table')
    op.drop_index(op.f('ix_oauth_account_oauth_name'), table_name='oauth_account')
    op.drop_index(op.f('ix_oauth_account_account_id'), table_name='oauth_account')
    op.drop_table('oauth_account')
    op.drop_index(op.f('ix_notifications_table_user_id'), table_name='notifications_table')
    op.drop_table('notifications_table')
    op.drop_index(op.f('ix_analytics_table_user_id'), table_name='analytics_table')
    op.drop_table('analytics_table')
    op.drop_index(op.f('ix_user_table_email'), table_name='user_table')
    op.drop_table('user_table')
    op.drop_table('question_cards_table')
    # ### end Alembic commands ###
