"""Add cascade delete to questionnaire user_id

Revision ID: be9a42e7dda9
Revises: 8e059e1e4743
Create Date: 2025-10-17 23:42:48.164928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9a42e7dda9'
down_revision: Union[str, Sequence[str], None] = '8e059e1e4743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('questionnaire_table_user_id_fkey'), 'questionnaire_table', type_='foreignkey')
    op.create_foreign_key(None, 'questionnaire_table', 'user_table', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questionnaire_table', type_='foreignkey')
    op.create_foreign_key(op.f('questionnaire_table_user_id_fkey'), 'questionnaire_table', 'user_table', ['user_id'], ['id'])
    # ### end Alembic commands ###
