"""empty message

Revision ID: cb1f08d48d72
Revises: 93fb97caca28
Create Date: 2025-10-12 22:43:34.405467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1f08d48d72'
down_revision: Union[str, Sequence[str], None] = '93fb97caca28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions_table', sa.Column('pronunciation_tests_left', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions_table', 'pronunciation_tests_left')
    # ### end Alembic commands ###
