"""empty message

Revision ID: d1d2f081df84
Revises: f0e85e1b8ffc
Create Date: 2025-08-22 15:26:43.607203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d2f081df84'
down_revision: Union[str, Sequence[str], None] = 'f0e85e1b8ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_table', sa.Column('streak_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics_table', 'streak_days')
    # ### end Alembic commands ###
