"""empty message

Revision ID: ed2e786b76e9
Revises: 684a27479b07
Create Date: 2025-08-15 08:48:31.775183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2e786b76e9'
down_revision: Union[str, Sequence[str], None] = '684a27479b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_test_table', sa.Column('test_duration', sa.Integer(), nullable=True))
    op.add_column('practice_test_table', sa.Column('test_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_test_table', 'test_date')
    op.drop_column('practice_test_table', 'test_duration')
    # ### end Alembic commands ###
