"""empty message

Revision ID: f00673c0265f
Revises: d1d2f081df84
Create Date: 2025-08-26 09:33:07.433533

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = "f00673c0265f"
down_revision: Union[str, Sequence[str], None] = "d1d2f081df84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_card_table",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column(
            "subscription_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
        sa.Column("stripe_payment_method_id", sa.String(length=64), nullable=False),
        sa.Column("card_holder_name", sa.String(length=150), nullable=False),
        sa.Column("card_type", sa.String(length=30), nullable=False),
        sa.Column("last_four", sa.String(length=4), nullable=False),
        sa.Column("expirty_date", sa.String(length=7), nullable=False),
        sa.Column("country", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions_table.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("credit_card_table")
    # ### end Alembic commands ###
