"""empty message

Revision ID: f0e85e1b8ffc
Revises: d861d655c240
Create Date: 2025-08-20 11:33:19.555503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e85e1b8ffc'
down_revision: Union[str, Sequence[str], None] = 'd861d655c240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reading_cards_table', 'practice_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reading_cards_table', 'practice_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
